substitutions:
  sensor_id: "1"
  humidity_name: "Humidity"
  humidity_disabled_by_default: false
  humidity_entity_category: ""
  temperature_name: "Temperature"
  temperature_disabled_by_default: false
  temperature_entity_category: ""
  update_interval: "60s"

esphome:
  name: dht-sensor
  project:
    name: curtistinkers.dht-sensor
    version: 1.0.0
  on_boot:
    - priority: -100
      then:
        # Update temperature, otherwise takes 60s to update for the first time.
        - component.update: sensor_dht_${sensor_id}

packages:
  humidity-offset: !include
    file: humidity-offset.yaml
    vars:
      sensor_id: ${sensor_id}
      humidity_name: ${humidity_name}
  temperature-offset: !include
    file: temperature-offset.yaml
    vars:
      sensor_id: ${sensor_id}
      temperature_name: ${temperature_name}
  
sensor:
  - platform: dht
    id: sensor_dht_${sensor_id}
    pin: ${pin}
    update_interval: ${update_interval}
    humidity:
      id: sensor_dht_${sensor_id}_humidity
      name: ${humidity_name}
      icon: "mdi:water-opacity"
      entity_category: ${humidity_entity_category}
      disabled_by_default: ${humidity_disabled_by_default}     
      filters:
        - lambda: return x + id(number_humidity_offset_${sensor_id}).state;
    
    temperature:
      id: sensor_dht_${sensor_id}_temperature
      name: ${temperature_name}
      icon: "mdi:thermometer"
      entity_category: ${temperature_entity_category}
      disabled_by_default: ${temperature_disabled_by_default}
      filters:
        - lambda: return x + id(number_temperature_offset_${sensor_id}).state;
