esphome:
  name: debug-base
  project:
    name: curtistinkers.debug-base
    version: 1.0.0

# Logger must be at least debug (default)
logger:
  level: debug

debug:
  update_interval: 10s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      entity_category: "diagnostic"
      disabled_by_default: true
    reset_reason:
      name: "Reset Reason"
      entity_category: "diagnostic"
      disabled_by_default: true

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      entity_category: "diagnostic"
      disabled_by_default: true
    block:
      name: "Heap Max Block"
      entity_category: "diagnostic"
      disabled_by_default: true
    fragmentation:
      name: "Heap Fragmentation"
      entity_category: "diagnostic"
      disabled_by_default: true
    loop_time:
      name: "Loop Time"
      entity_category: "diagnostic"
      disabled_by_default: true
    psram:
      name: "Free PSRAM"
      disabled_by_default: true
    cpu_frequency:
      name: "CPU Frequency"
      entity_category: "diagnostic"
      disabled_by_default: true
